### ISSUE TITLE
Performance Question

### ISSUE THREAD

**Issue by RuiAAPeres** [delba/JASON#6]
The speed/performance of this library is mentioned twice:

> JASON is a faster JSON deserializer written in Swift.

And in the quote:

> _(...) This is by far the fastest and the most convenient out there (...)_

Are there any measurements/benchmarks to back these claims?

**Comment by delba** [comment]
Hi @RuiAAPeres, thanks for the issue.

Yes, there is a [`benchmarks`](https://github.com/delba/JASON/tree/benchmarks) branch linked in the "Features" section. I will update the benchmarks with the latest versions of the libs but we should get a similar result as the implementations didn't change.

The two projects have a very similar API but, internally, `JASON` is using `NSArray` and `NSDictionary` instead of `[AnyObject]` and `[String: AnyObject]`. The PRs on the other project that proposed to use to `NSArray`/`NSDictionary` were rejected. This is one of the reasons (but not the only one) I created `JASON`.

However I realize it can appear as "cocky" and I don't want to draw attention by bashing another OS project. But on the other hand, I think that the perf benefits are really worth mentioning. What do you think? (btw feel free to mail me at damien@delba.io)

**Comment by delba** [comment]
@RuiAAPeres The [`benchmarks`](https://github.com/delba/JASON/tree/benchmarks) branch has been updated to use the latest versions of the libraries.

Two things to note:
- both libraries are now **much** faster than before
- `JASON` is now "only" 2 times faster

See the [diff](https://github.com/delba/JASON/commit/8c7aa3aa79ba5726cb897027b76a66d771636f0b#diff-04c6e90faac2675aa89e2176d2eec7d8L34)
